# Generated by Django 5.2.3 on 2025-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('traffic_source', models.CharField(choices=[('direct', 'Direct'), ('social', 'Social'), ('search', 'Search Engine'), ('referral', 'Referral')], default='direct', max_length=20)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['page_url', 'date'], name='analytics_p_page_ur_c02477_idx'), models.Index(fields=['traffic_source', 'date'], name='analytics_p_traffic_b9cace_idx'), models.Index(fields=['date'], name='analytics_p_date_cdf4b5_idx')],
            },
        ),
    ]
