# Generated by Django 5.2.3 on 2025-07-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_title',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/profile_images/'),
        ),
    ]
