# Generated by Django 5.2.3 on 2025-07-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_canonical_url_post_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes.'),
        ),
    ]
