# Generated by Django 5.2.3 on 2025-07-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_page_alter_post_options_post_post_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
