# Generated by Django 5.2.3 on 2025-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_page_featured_image_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
