# Generated by Django 5.2.3 on 2025-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('area_of_expertise', models.CharField(choices=[('house_job', 'House Job Mentorship'), ('nigerian_residency', 'Nigerian Residency Mentorship'), ('usmle_canada', 'USMLE/Canada Residency Mentorship'), ('amc_plab', 'AMC/PLAB Pathway Mentorship'), ('mph', 'US/UK/Canada MPH Mentorship'), ('express_entry', 'Canadian Express Entry Mentorship'), ('non_clinical', 'Non-clinical Role Mentorship'), ('mdcn_exam', 'MDCN Exam')], max_length=50)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('bio', models.TextField(help_text='Short professional bio')),
                ('cv', models.FileField(upload_to='mentors/cv/')),
                ('certificate', models.FileField(upload_to='mentors/certificates/')),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
