# Generated by Django 5.2.3 on 2025-07-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mentorapplication_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorapplication',
            old_name='reviewed',
            new_name='rejected',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='admin_notes',
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='job_title',
            field=models.CharField(help_text='Current professional job title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='professional_picture',
            field=models.ImageField(null=True, upload_to='mentors/profile_pictures/'),
        ),
    ]
