# Generated by Django 5.2.3 on 2025-07-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_reviewed_mentorapplication_rejected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('mentorship_choice', models.CharField(choices=[('house_job', 'House Job Mentorship'), ('nigerian_residency', 'Nigerian Residency Mentorship'), ('usmle_canada', 'USMLE/Canada Residency Mentorship'), ('amc_plab', 'AMC/PLAB Pathway Mentorship'), ('mph', 'US/UK/Canada MPH Mentorship'), ('express_entry', 'Canadian Express Entry Mentorship'), ('non_clinical', 'Non-clinical Role Mentorship'), ('mdcn_exam', 'MDCN Exam')], max_length=50)),
                ('amount_paid', models.PositiveIntegerField(editable=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
