# Generated by Django 5.2.3 on 2025-07-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapplication',
            name='certificate',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='cv',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='professional_picture',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
