# Generated by Django 5.2.3 on 2025-09-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('analytics_consent', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('necessary_consent', models.BooleanField(default=True)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cookie_consent',
            },
        ),
    ]
