# Generated by Django 5.2.3 on 2025-09-15 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cookieconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('house_job', 'House Job Mentorship'), ('nigerian_residency', 'Nigerian Residency Mentorship'), ('usmle_canada', 'USMLE/Canada Residency Mentorship'), ('amc_plab', 'AMC/PLAB Pathway Mentorship'), ('mph', 'US/UK/Canada MPH Mentorship'), ('express_entry', 'Canadian Express Entry Mentorship'), ('non_clinical', 'Non-clinical Role Mentorship'), ('mdcn_exam', 'MDCN Exam')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='mentorshipapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.RemoveField(
            model_name='mentorshipapplication',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='mentorshipapplication',
            name='mentorship_choice',
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mentorshipapplication',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='mentorship_programs',
            field=models.ManyToManyField(related_name='applications', to='main.mentorshipprogram'),
        ),
    ]
