# Generated by Django 5.2.3 on 2025-09-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mentorshipprogram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipapplication',
            name='mentorship_programs',
        ),
        migrations.RenameField(
            model_name='mentorshipapplication',
            old_name='payment_date',
            new_name='payment_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='mentorshipapplication',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='mentorshipapplication',
            index=models.Index(fields=['email'], name='main_mentor_email_ddbbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipapplication',
            index=models.Index(fields=['is_paid'], name='main_mentor_is_paid_ade468_idx'),
        ),
        migrations.DeleteModel(
            name='MentorshipProgram',
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='mentorship_programs',
            field=models.JSONField(default=list, help_text='List of selected mentorship programs'),
        ),
    ]
