# Generated by Django 5.2.3 on 2025-07-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='category',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('spreadsheets', 'Spreadsheets'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
