# Generated by Django 5.2.3 on 2025-07-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0002_remove_mediafile_uploaded_by_mediafile_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media Library'},
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='title',
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='category',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
